### PR TITLE
feat: add alert and button components

### PR DESCRIPTION
**Pull request by irfan-nawaz**
this repository consists of various buttons and alerts for the component library, also I have defined typography color and spacing variables for creating components.

### CODE REVIEW

**Review by mohammed-sas — CHANGES_REQUESTED** [review]
suggestion : it's better to use box shadow only when specified . remove the box shadows for button and alerts

**Review by mohammed-sas — APPROVED** [review]
good for merge

**Review by Kevin-Solomon — COMMENTED** [review]
Just a suggestion it would be better for the reviewer if you could paste the screenshots of the components or even have a codesandbox link while making the PR description.
If it is a bug fix then a before and after screenshot would be nice.
Other than these minor changes everything else looks fine. Great job!!

**Review by Kevin-Solomon — APPROVED** [review]

**Comment by irfan-nawaz** [comment]
[Preview](https://ui-view.netlify.app/)

**Pull request merged**
